pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                // Check Maven version
                sh 'mvn --version'
                
                // Compile the Java program using Maven
                sh 'mvn compile'

                // Run the Java program (Ensure the class name is correct)
                sh 'java -cp target/classes HelloWorld'  // Adjust the class name or add package if needed
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                // Check Node.js version
                sh 'node --version'
            }
        }
    }
}
