pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                // Check Maven version
                sh 'mvn --version'
                sh 'ls -la'
                sh 'javac src/HelloWorld.java'
                sh 'java -cp src HelloWorld'
        }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                // Check Node.js version
                sh 'node --version'
            }
        }
    }
}
